name: Build and publish docker image

# Configures this workflow to run manually from the GitHub Actions tab.
on:
  workflow_dispatch:
    inputs:
      postgres_version:
        description: 'Postgres version'
        required: true
        default: '16'

      postgis_version:
        description: 'PostGIS version'
        required: true
        default: '3.4'
        
      geos_version:
        description: 'GEOS version'
        required: true
        default: '3.12.1'
        

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.postgres_version }}-${{ github.event.inputs.postgis_version }}-${{ github.event.inputs.geos_version }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            POSTGRES_VERSION=${{ github.event.inputs.postgres_version }}
            POSTGIS_VERSION=${{ github.event.inputs.postgis_version }}
            GEOS_VERSION=${{ github.event.inputs.geos_version }}